version: "3.8"

services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api1
    ports:
      - "8081:8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api2
    ports:
      - "8082:8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"


  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"
 
  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:80"    # rota tráfego do host:9999 para o HAProxy na porta 80
      - "443:443"    # (opcional) se vier a usar SSL offload
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus:    "0.2"
          memory:  "25MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    driver: bridge
