version: "3.8"

services:
  api1:
    image: jorgedevsoftware/jorge-rinha:1.0
    container_name: api1
    environment:
      - "JAVA_OPTS=-Dserver.port=8081 -Xms54m -Xmx110m"
    ports:
      - "8081:8080"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "90MB"

  api2:
    image: jorgedevsoftware/jorge-rinha:1.0
    container_name: api2
    environment:
      - "JAVA_OPTS=-Dserver.port=8082 -Xms54m -Xmx110m"
    ports:
      - "8082:8080"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "90MB"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

networks:
  payment-processor:
    driver: bridge
